settings:
  legacy:
    force: false
    interval: 0s
server:
  host: 0.0.0.0
schema:
- name: workspace
  path: .
  commands:
    install:
      status: true
      method: make build
    run:
      status: true
      method: bin/server
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
    - containers
    - .devcontainers
