version: '3'
services:
  dev:
    build:
      context: containers/dev
      dockerfile: Dockerfile
    ports:
      - 9080:9080
    volumes:
      - .:/root/workspace
    command: tail -f /dev/null
    working_dir: /root/workspace
